/* Migración Definitiva: Crear tabla carreras y enlazar datos existentes */

/* 1. Crear tabla carreras */
CREATE TABLE IF NOT EXISTS public.carreras (
    id bigint generated by default as identity primary key,
    nombre text not null unique,
    facultad_id bigint,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

/* 2. Insertar TODO el catálogo oficial de carreras primero */
INSERT INTO public.carreras (nombre)
VALUES 
    ('Administración de Empresas'),
    ('Arquitectura'),
    ('Ciencia de Datos'),
    ('Ciencia Política y Gobierno'),
    ('Comunicación Social y Periodismo'),
    ('Contaduría Pública'),
    ('Derecho'),
    ('Diseño Gráfico'),
    ('Diseño Industrial'),
    ('Economía'),
    ('Geología'),
    ('Ingeniería Civil'),
    ('Ingeniería de Sistemas'),
    ('Ingeniería Eléctrica'),
    ('Ingeniería Industrial'),
    ('Ingeniería Mecánica'),
    ('Lenguas Modernas y Cultura'),
    ('Medicina'),
    ('Música'),
    ('Negocios Internacionales'),
    ('Odontología'),
    ('Psicología'),
    ('Relaciones Internacionales'),
    ('Funcionarios'),
    ('Egresados')
ON CONFLICT (nombre) DO NOTHING;

/* 2.1 Insertar cualquier carrera extra (escrita a mano) que ya esté en partidos/medallero */
INSERT INTO public.carreras (nombre)
SELECT DISTINCT equipos.equipo FROM (
    SELECT equipo_a as equipo FROM public.partidos WHERE equipo_a IS NOT NULL AND trim(equipo_a) != ''
    UNION
    SELECT equipo_b as equipo FROM public.partidos WHERE equipo_b IS NOT NULL AND trim(equipo_b) != ''
    UNION
    SELECT equipo_nombre as equipo FROM public.medallero WHERE equipo_nombre IS NOT NULL AND trim(equipo_nombre) != ''
) as equipos
WHERE equipos.equipo NOT IN (SELECT nombre FROM public.carreras)
ON CONFLICT (nombre) DO NOTHING;

/* 3. Añadir columnas de ID a partidos (si no existen) */
DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='partidos' AND column_name='carrera_a_id') THEN
        ALTER TABLE public.partidos ADD COLUMN carrera_a_id bigint references public.carreras(id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='partidos' AND column_name='carrera_b_id') THEN
        ALTER TABLE public.partidos ADD COLUMN carrera_b_id bigint references public.carreras(id);
    END IF;
END $$;

/* 4. Actualizar partidos existentes con los IDs de las carreras correspondientes */
UPDATE public.partidos p
SET carrera_a_id = c.id
FROM public.carreras c
WHERE p.equipo_a = c.nombre;

UPDATE public.partidos p
SET carrera_b_id = c.id
FROM public.carreras c
WHERE p.equipo_b = c.nombre;

/* 5. Añadir columna a medallero (si no existe) */
DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='medallero' AND column_name='carrera_id') THEN
        ALTER TABLE public.medallero ADD COLUMN carrera_id bigint references public.carreras(id);
    END IF;
END $$;

/* 6. Actualizar medallero existente */
UPDATE public.medallero m
SET carrera_id = c.id
FROM public.carreras c
WHERE m.equipo_nombre = c.nombre;

/* 7. Activar RLS para la nueva tabla y crear políticas */
ALTER TABLE public.carreras ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Carreras son públicas" ON public.carreras;
CREATE POLICY "Carreras son públicas" 
ON public.carreras FOR SELECT USING (true);

DROP POLICY IF EXISTS "Solo admin puede insertar carreras" ON public.carreras;
CREATE POLICY "Solo admin puede insertar carreras" 
ON public.carreras FOR INSERT WITH CHECK (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Solo admin puede actualizar carreras" ON public.carreras;
CREATE POLICY "Solo admin puede actualizar carreras" 
ON public.carreras FOR UPDATE USING (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Solo admin puede borrar carreras" ON public.carreras;
CREATE POLICY "Solo admin puede borrar carreras" 
ON public.carreras FOR DELETE USING (auth.role() = 'authenticated');

/* 8. Asegurar que la tabla transmita cambios por Realtime */
DO $$ 
BEGIN
    If not exists (
      select 1 from pg_publication_tables 
      where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'carreras'
    ) THEN
      alter publication supabase_realtime add table public.carreras;
    END IF;
END $$;
