CREATE TABLE IF NOT EXISTS public.medallero (
    id bigint generated by default as identity primary key,
    equipo_nombre text not null unique,
    oro integer default 0,
    plata integer default 0,
    bronce integer default 0,
    puntos integer default 0,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);
ALTER PUBLICATION supabase_realtime ADD TABLE public.medallero;
