-- ============================================
-- ACTUALIZACIÓN DE SCHEMA PARA EVENTOS EN VIVO
-- ============================================

-- Tabla de Jugadores/Participantes
create table if not exists jugadores (
  id bigint generated by default as identity primary key,
  nombre text not null,
  numero int,
  equipo text not null, -- 'equipo_a' o 'equipo_b'
  partido_id bigint references partidos(id) on delete cascade,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Tabla de Eventos del Partido
create table if not exists eventos_partido (
  id bigint generated by default as identity primary key,
  partido_id bigint references partidos(id) on delete cascade not null,
  tipo_evento text not null, -- 'gol', 'tarjeta_amarilla', 'tarjeta_roja', 'inicio', 'fin'
  minuto int not null,
  jugador_id bigint references jugadores(id),
  equipo text not null, -- 'equipo_a' o 'equipo_b'
  descripcion text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Añadir columnas al marcador_detalle para el cronómetro
-- Ya existe marcador_detalle como JSONB, así que agregaremos:
-- {
--   "tiempo_inicio": timestamp,
--   "minuto_actual": 0,
--   "estado_cronometro": "detenido" | "corriendo" | "pausado"
-- }

-- Índices para mejor performance
create index if not exists idx_jugadores_partido on jugadores(partido_id);
create index if not exists idx_eventos_partido on eventos_partido(partido_id);

-- RLS Policies
alter table jugadores enable row level security;
alter table eventos_partido enable row level security;

create policy "Jugadores are viewable by everyone" 
  on jugadores for select using (true);

create policy "Eventos are viewable by everyone" 
  on eventos_partido for select using (true);

create policy "Enable insert for authenticated users" 
  on jugadores for insert with check (true);

create policy "Enable insert for authenticated users eventos" 
  on eventos_partido for insert with check (true);

create policy "Enable update for authenticated users" 
  on jugadores for update using (true);

create policy "Enable delete for authenticated users" 
  on jugadores for delete using (true);
