-- Tipos de Usuario (Enum)
create type user_role as enum ('admin', 'data_entry', 'public');

-- Tabla de Perfiles (Extiende la tabla auth.users de Supabase)
create table profiles (
  id uuid references auth.users on delete cascade not null primary key,
  email text,
  role user_role default 'public',
  full_name text,
  assigned_discipline_id bigint references disciplinas(id),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Tabla de Disciplinas
create table disciplinas (
  id bigint generated by default as identity primary key,
  name text not null,
  icon text -- nombre del icono (lucide)
);

-- Insertar disciplinas base
insert into disciplinas (name, icon) values 
('Fútbol', 'futbol'),
('Baloncesto', 'basketball'),
('Voleibol', 'volleyball'),
('Tenis', 'tennis'),
('Ajedrez', 'chess-knight'),
('Natación', 'waves'),
('Tenis de Mesa', 'table-tennis');

-- Tabla de Partidos / Eventos
create table partidos (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  disciplina_id bigint references disciplinas(id) not null,
  
  -- Info General
  equipo_a text not null, -- Nombre del equipo/jugador A
  equipo_b text not null, -- Nombre del equipo/jugador B
  fecha timestamp with time zone not null,
  estado text default 'programado', -- programado, en_vivo, finalizado
  
  -- Marcador en Tiempo Real (JSONB FLEXIBLE)
  -- Aquí guardaremos la estructura específica de cada deporte (goles, sets, etc.)
  -- Ej: { "goles_a": 1, "goles_b": 0, "detalles": [...] }
  marcador_detalle jsonb default '{}'::jsonb,
  
  -- Responsable de actualizar este partido (opcional)
  responsable_id uuid references auth.users(id)
);

-- Habilitar Realtime para la tabla partidos
alter publication supabase_realtime add table partidos;

-- POLÍTICAS DE SEGURIDAD (RLS) --

alter table profiles enable row level security;
alter table partidos enable row level security;

-- 1. Lectura pública para todos
create policy "Public profiles are viewable by everyone" on profiles for select using (true);
create policy "Partidos are viewable by everyone" on partidos for select using (true);

-- 2. Solo Admins pueden crear/editar todo (Simplificado para este ejemplo)
-- En producción, se usaría un check( auth.uid() in (select id from profiles where role = 'admin') )

-- 3. Data Entry solo puede editar sus partidos asignados
create policy "Data Entry can update own matches" on partidos for update
  using ( auth.uid() = responsable_id )
  using ( auth.uid() = responsable_id )
  with check ( auth.uid() = responsable_id );

-- 4. Permitir crear partidos (Demo/Desarrollo)
create policy "Enable insert for everyone" on partidos for insert with check (true);

-- 5. Permitir actualizar a todos (simplificado para Demo, luego restringir a admin)
create policy "Enable update for everyone" on partidos for update using (true);

