-- MIGRATION GENERATED BY import_jornadas.js
DO $$
DECLARE
    v_ajedrez_id BIGINT;
    v_tenis_id BIGINT;
BEGIN
    SELECT id INTO v_ajedrez_id FROM disciplinas WHERE name ILIKE 'Ajedrez' LIMIT 1;
    SELECT id INTO v_tenis_id FROM disciplinas WHERE name ILIKE 'Tenis de Mesa' LIMIT 1;

    INSERT INTO jornadas (disciplina_id, genero, numero, nombre, scheduled_at, lugar, estado)
    VALUES 
        (v_ajedrez_id, 'mixto', 1, 'Ronda 1', '2026-04-17T14:00:00-05:00', 'Lobby Sur del Coliseo', 'programado'),
        (v_tenis_id, 'mixto', 1, 'Jornada 1', '2026-04-17T13:00:00-05:00', 'Cacha Central del Coliseo', 'programado'),
        (v_tenis_id, 'mixto', 2, 'Jornada 2', '2026-04-24T13:00:00-05:00', 'Cacha Central del Coliseo', 'programado')
    ON CONFLICT (disciplina_id, genero, numero) DO UPDATE SET
        nombre = EXCLUDED.nombre,
        scheduled_at = EXCLUDED.scheduled_at,
        lugar = EXCLUDED.lugar;
END $$;
