-- ============================================
-- SCRIPT DE CORRECCIÓN: NOMBRES ÚNICOS
-- ============================================

-- 1. Limpiar tablas viejas (si existen)
drop table if exists public.eventos_partido cascade;
drop table if exists public.jugadores cascade;

-- 2. Crear Tabla JUGADORES (Tabla nueva: olympics_jugadores)
create table if not exists public.olympics_jugadores (
  id bigint generated by default as identity primary key,
  nombre text not null,
  numero int,
  equipo text not null, 
  partido_id bigint references public.partidos(id) on delete cascade,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Crear Tabla EVENTOS (Tabla nueva: olympics_eventos)
create table if not exists public.olympics_eventos (
  id bigint generated by default as identity primary key,
  partido_id bigint references public.partidos(id) on delete cascade not null,
  tipo_evento text not null,
  minuto int not null,
  jugador_id bigint references public.olympics_jugadores(id),
  equipo text not null,
  descripcion text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. POLÍTICAS DE SEGURIDAD (RLS)
-- IMPORTANTE: Habilitamos RLS pero permitimos TODO para evitar problemas de caché
alter table public.olympics_jugadores enable row level security;
alter table public.olympics_eventos enable row level security;

-- Permitir todo: Select, Insert, Update, Delete
create policy "Todas las operaciones permitidas jugadores" 
  on public.olympics_jugadores for all 
  using (true) 
  with check (true);

create policy "Todas las operaciones permitidas eventos" 
  on public.olympics_eventos for all 
  using (true) 
  with check (true);

-- 5. Índices para velocidad
create index on public.olympics_jugadores(partido_id);
create index on public.olympics_eventos(partido_id);
