-- Tabla de Medallero General
CREATE TABLE IF NOT EXISTS medallero (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    equipo_nombre TEXT NOT NULL UNIQUE,  -- Ej: "Ingeniería", "Medicina", "Derecho"
    oro INT DEFAULT 0,
    plata INT DEFAULT 0,
    bronce INT DEFAULT 0,
    puntos INT DEFAULT 0, -- Puntos calculados (Oro=5, Plata=3, Bronce=1, etc. o manual)
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Habilitar Realtime
ALTER PUBLICATION supabase_realtime ADD TABLE medallero;

-- Políticas de Seguridad (RLS)
ALTER TABLE medallero ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public read medallero" ON medallero FOR SELECT USING (true);
CREATE POLICY "Admin update medallero" ON medallero FOR ALL USING (true); -- Simplificado para desarrollo

-- Datos de ejemplo
INSERT INTO medallero (equipo_nombre, oro, plata, bronce, puntos) VALUES
('Ingeniería', 5, 2, 1, 32),
('Medicina', 3, 4, 2, 29),
('Derecho', 2, 1, 5, 18),
('Arquitectura', 1, 3, 2, 16),
('Psicología', 0, 2, 4, 10)
ON CONFLICT (equipo_nombre) DO NOTHING;
