-- TABLA JUGADORES
create table if not exists public.jugadores (
  id bigint generated by default as identity primary key,
  nombre text not null,
  numero int,
  equipo text not null, 
  partido_id bigint references public.partidos(id) on delete cascade,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- TABLA EVENTOS
create table if not exists public.eventos_partido (
  id bigint generated by default as identity primary key,
  partido_id bigint references public.partidos(id) on delete cascade not null,
  tipo_evento text not null,
  minuto int not null,
  jugador_id bigint references public.jugadores(id),
  equipo text not null,
  descripcion text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- POLÍTICAS DE SEGURIDAD (RLS) - Permite todo para facilitar
alter table public.jugadores enable row level security;
alter table public.eventos_partido enable row level security;

create policy "Permitir todo jugadores" on public.jugadores for all using (true) with check (true);
create policy "Permitir todo eventos" on public.eventos_partido for all using (true) with check (true);
