-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
-- Migration: Delegaciones — Olympic team representation per sport
-- Date: 2026-03-30
-- Description:
--   A "delegación" is a team that represents one or more careers in a specific
--   sport+gender. This allows career fusions (e.g., "Ing. Eléctrica / Ciencia
--   de Datos" as one team) while keeping individual career identity for shared
--   point attribution.
--
--   Changes:
--   1. Create delegaciones table
--   2. Add delegacion_a_id / delegacion_b_id FKs to partidos
--   3. Add carrera_a_ids / carrera_b_ids arrays to partidos (denormalized for
--      efficient profile queries and shared-point stats)
--   4. Backfill arrays from existing carrera_a_id / carrera_b_id values
-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

-- ─────────────────────────────────────────────────────────────────────────────
-- 1. Table: delegaciones
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.delegaciones (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre        TEXT NOT NULL,
    -- Display name as shown in the schedule (e.g., "Ing. Eléctrica / Ciencia de Datos")
    disciplina_id BIGINT REFERENCES public.disciplinas(id) ON DELETE SET NULL,
    genero        TEXT CHECK (genero IN ('masculino', 'femenino', 'mixto') OR genero IS NULL),
    carrera_ids   BIGINT[] NOT NULL DEFAULT '{}',
    -- IDs of ALL careers in this team.
    -- Single-career teams: [carrera_id]. Fusions: [id1, id2, ...].
    -- Used to distribute medals and points to every participating career.
    slot_label    TEXT,
    -- Tournament draw slot (e.g., "1A", "2B"). NULL until admin seeds the draw.
    created_at    TIMESTAMPTZ DEFAULT now() NOT NULL,

    UNIQUE NULLS NOT DISTINCT (disciplina_id, genero, nombre)
);

COMMENT ON TABLE public.delegaciones IS
'Olympic participating teams per sport+gender. May represent one career (solo)
or multiple (fusion). carrera_ids lists all careers for shared-point attribution.
slot_label links the team to its tournament bracket slot (assigned post-draw).';

-- ─────────────────────────────────────────────────────────────────────────────
-- 2. Add delegation FK columns and carrera ID array columns to partidos
-- ─────────────────────────────────────────────────────────────────────────────

ALTER TABLE public.partidos
    ADD COLUMN IF NOT EXISTS delegacion_a_id BIGINT
        REFERENCES public.delegaciones(id) ON DELETE SET NULL,
    ADD COLUMN IF NOT EXISTS delegacion_b_id BIGINT
        REFERENCES public.delegaciones(id) ON DELETE SET NULL,
    -- Denormalized arrays. Populated when a delegation is assigned to a match:
    --   solo career  → [carrera_id]      (also sets carrera_a_id for backward compat)
    --   fusion       → [id1, id2, ...]   (carrera_a_id stays NULL)
    ADD COLUMN IF NOT EXISTS carrera_a_ids BIGINT[] NOT NULL DEFAULT '{}',
    ADD COLUMN IF NOT EXISTS carrera_b_ids BIGINT[] NOT NULL DEFAULT '{}';

-- ─────────────────────────────────────────────────────────────────────────────
-- 3. Backfill arrays from existing single-carrera FKs
-- ─────────────────────────────────────────────────────────────────────────────

UPDATE public.partidos
SET carrera_a_ids = ARRAY[carrera_a_id]
WHERE carrera_a_id IS NOT NULL
  AND carrera_a_ids = '{}';

UPDATE public.partidos
SET carrera_b_ids = ARRAY[carrera_b_id]
WHERE carrera_b_id IS NOT NULL
  AND carrera_b_ids = '{}';

-- ─────────────────────────────────────────────────────────────────────────────
-- 4. Indexes
-- ─────────────────────────────────────────────────────────────────────────────

CREATE INDEX IF NOT EXISTS idx_delegaciones_disciplina_genero
    ON public.delegaciones (disciplina_id, genero);

-- GIN indexes for array containment queries (@>)
-- Used by useCarreraProfile to find all matches for a given career (incl. fusions)
CREATE INDEX IF NOT EXISTS idx_partidos_carrera_a_ids
    ON public.partidos USING GIN (carrera_a_ids);

CREATE INDEX IF NOT EXISTS idx_partidos_carrera_b_ids
    ON public.partidos USING GIN (carrera_b_ids);

CREATE INDEX IF NOT EXISTS idx_partidos_delegacion_a
    ON public.partidos (delegacion_a_id);

CREATE INDEX IF NOT EXISTS idx_partidos_delegacion_b
    ON public.partidos (delegacion_b_id);

-- ─────────────────────────────────────────────────────────────────────────────
-- 5. Backfill delegaciones from existing partidos
--    Runs idempotently: ON CONFLICT DO NOTHING preserves manual edits.
--    Covers only rows NOT yet created (e.g., fixtures imported before this migration).
-- ─────────────────────────────────────────────────────────────────────────────

INSERT INTO public.delegaciones (nombre, disciplina_id, genero, carrera_ids)
SELECT
    nombre,
    disciplina_id,
    genero,
    COALESCE(
        ARRAY_AGG(DISTINCT carrera_id) FILTER (WHERE carrera_id IS NOT NULL),
        '{}'::BIGINT[]
    ) AS carrera_ids
FROM (
    SELECT
        equipo_a                AS nombre,
        disciplina_id,
        genero,
        carrera_a_id            AS carrera_id
    FROM public.partidos
    WHERE equipo_a IS NOT NULL
      AND TRIM(equipo_a) <> ''
      AND equipo_a NOT ILIKE '%por definir%'
      AND disciplina_id IS NOT NULL
      AND genero IS NOT NULL

    UNION ALL

    SELECT
        equipo_b                AS nombre,
        disciplina_id,
        genero,
        carrera_b_id            AS carrera_id
    FROM public.partidos
    WHERE equipo_b IS NOT NULL
      AND TRIM(equipo_b) <> ''
      AND equipo_b NOT ILIKE '%por definir%'
      AND disciplina_id IS NOT NULL
      AND genero IS NOT NULL
) t
GROUP BY nombre, disciplina_id, genero
ON CONFLICT (disciplina_id, genero, nombre) DO NOTHING;

-- Back-link partidos → delegaciones
UPDATE public.partidos p
SET delegacion_a_id = d.id
FROM public.delegaciones d
WHERE d.nombre = p.equipo_a
  AND d.disciplina_id = p.disciplina_id
  AND d.genero = p.genero
  AND p.delegacion_a_id IS NULL;

UPDATE public.partidos p
SET delegacion_b_id = d.id
FROM public.delegaciones d
WHERE d.nombre = p.equipo_b
  AND d.disciplina_id = p.disciplina_id
  AND d.genero = p.genero
  AND p.delegacion_b_id IS NULL;

-- ─────────────────────────────────────────────────────────────────────────────
-- 6. RLS
-- ─────────────────────────────────────────────────────────────────────────────

ALTER TABLE public.delegaciones ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "delegaciones_public_read" ON public.delegaciones;
DROP POLICY IF EXISTS "delegaciones_admin_write" ON public.delegaciones;

CREATE POLICY "delegaciones_public_read"
    ON public.delegaciones FOR SELECT
    USING (true);

CREATE POLICY "delegaciones_admin_write"
    ON public.delegaciones FOR ALL
    USING (public.has_role(auth.uid(), 'admin'))
    WITH CHECK (public.has_role(auth.uid(), 'admin'));

-- ─────────────────────────────────────────────────────────────────────────────
-- 7. Realtime
-- ─────────────────────────────────────────────────────────────────────────────

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_publication_tables
        WHERE pubname   = 'supabase_realtime'
          AND schemaname = 'public'
          AND tablename  = 'delegaciones'
    ) THEN
        ALTER PUBLICATION supabase_realtime ADD TABLE public.delegaciones;
    END IF;
END $$;

-- Reload PostgREST schema cache
NOTIFY pgrst, 'reload schema';
