-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
-- Migration: Olympic Points System
-- Date: 2026-03-24
-- Description:
--   Implements the UNorte Olympics points system:
--   1. puntos_config — configurable points per finishing position per sport type
--   2. clasificacion_disciplina — admin records final positions per discipline
--   3. view_clasificacion_general — total points per carrera (public leaderboard)
-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

-- ═══════════════════════════════════════════════════════════════════════════════
-- TABLE: puntos_config
-- Points awarded per finishing position, split by sport type.
-- tipo_deporte: 'equipo' (team), 'individual', 'barras' (crowd/cheering)
-- posicion: 1 = 1st place, 8 = last
-- ═══════════════════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS public.puntos_config (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_deporte    TEXT NOT NULL,
    posicion        INT NOT NULL CHECK (posicion BETWEEN 1 AND 8),
    puntos          INT NOT NULL CHECK (puntos >= 0),
    descripcion     TEXT,
    created_at      TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    updated_at      TIMESTAMPTZ DEFAULT NOW() NOT NULL,

    UNIQUE(tipo_deporte, posicion)
);

COMMENT ON TABLE public.puntos_config IS
'Configurable Olympic points per finishing position per sport type.
Edited by admins; referenced by clasificacion_disciplina to compute totals.';

-- Seed default values (adjustable by admins via UI)
INSERT INTO public.puntos_config (tipo_deporte, posicion, puntos, descripcion) VALUES
-- Team sports: Fútbol, Baloncesto, Voleibol
('equipo', 1, 15, '1er lugar — Deporte Colectivo'),
('equipo', 2, 12, '2do lugar — Deporte Colectivo'),
('equipo', 3, 10, '3er lugar — Deporte Colectivo'),
('equipo', 4,  8, '4to lugar — Deporte Colectivo'),
('equipo', 5,  6, '5to lugar — Deporte Colectivo'),
('equipo', 6,  4, '6to lugar — Deporte Colectivo'),
('equipo', 7,  2, '7mo lugar — Deporte Colectivo'),
('equipo', 8,  1, '8vo lugar — Deporte Colectivo'),
-- Individual sports: Tenis, Tenis de Mesa, Ajedrez, Natación
('individual', 1, 10, '1er lugar — Deporte Individual'),
('individual', 2,  8, '2do lugar — Deporte Individual'),
('individual', 3,  6, '3er lugar — Deporte Individual'),
('individual', 4,  5, '4to lugar — Deporte Individual'),
('individual', 5,  4, '5to lugar — Deporte Individual'),
('individual', 6,  3, '6to lugar — Deporte Individual'),
('individual', 7,  2, '7mo lugar — Deporte Individual'),
('individual', 8,  1, '8vo lugar — Deporte Individual'),
-- Barras (crowd/cheering) — 3 positions
('barras', 1,  8, '1er lugar — Barras'),
('barras', 2,  5, '2do lugar — Barras'),
('barras', 3,  3, '3er lugar — Barras')
ON CONFLICT (tipo_deporte, posicion) DO NOTHING;

-- RLS
ALTER TABLE public.puntos_config ENABLE ROW LEVEL SECURITY;

CREATE POLICY "puntos_config_select_all"
    ON public.puntos_config FOR SELECT USING (true);

CREATE POLICY "puntos_config_all_admins"
    ON public.puntos_config FOR ALL
    USING (public.has_role(auth.uid(), 'admin'))
    WITH CHECK (public.has_role(auth.uid(), 'admin'));


-- ═══════════════════════════════════════════════════════════════════════════════
-- TABLE: clasificacion_disciplina
-- Admin records which carrera finished at which position in each discipline.
-- puntos_obtenidos is snapshotted from puntos_config at time of entry
-- (stored so config changes don't retroactively alter historical results).
-- ═══════════════════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS public.clasificacion_disciplina (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    disciplina_id   BIGINT NOT NULL REFERENCES public.disciplinas(id) ON DELETE CASCADE,
    carrera_id      BIGINT NOT NULL REFERENCES public.carreras(id) ON DELETE CASCADE,
    genero          TEXT NOT NULL DEFAULT 'masculino'
                    CHECK (genero IN ('masculino', 'femenino', 'mixto')),
    posicion        INT NOT NULL CHECK (posicion BETWEEN 1 AND 8),
    puntos_obtenidos INT NOT NULL DEFAULT 0,
    notas           TEXT,
    created_at      TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    updated_at      TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    created_by      UUID REFERENCES public.profiles(id) ON DELETE SET NULL,

    UNIQUE(disciplina_id, carrera_id, genero)
);

COMMENT ON TABLE public.clasificacion_disciplina IS
'Final Olympic positions per discipline per carrera.
Points are snapshotted at entry time — config changes do not affect past entries.
view_clasificacion_general aggregates these for the public leaderboard.';

CREATE INDEX IF NOT EXISTS idx_clasificacion_disciplina_id
    ON public.clasificacion_disciplina(disciplina_id);
CREATE INDEX IF NOT EXISTS idx_clasificacion_carrera_id
    ON public.clasificacion_disciplina(carrera_id);

-- RLS
ALTER TABLE public.clasificacion_disciplina ENABLE ROW LEVEL SECURITY;

CREATE POLICY "clasificacion_select_all"
    ON public.clasificacion_disciplina FOR SELECT USING (true);

CREATE POLICY "clasificacion_insert_staff"
    ON public.clasificacion_disciplina FOR INSERT
    WITH CHECK (
        public.has_role(auth.uid(), 'admin')
        OR public.has_role(auth.uid(), 'data_entry')
    );

CREATE POLICY "clasificacion_update_staff"
    ON public.clasificacion_disciplina FOR UPDATE
    USING (
        public.has_role(auth.uid(), 'admin')
        OR public.has_role(auth.uid(), 'data_entry')
    );

CREATE POLICY "clasificacion_delete_admins"
    ON public.clasificacion_disciplina FOR DELETE
    USING (public.has_role(auth.uid(), 'admin'));


-- ═══════════════════════════════════════════════════════════════════════════════
-- VIEW: view_clasificacion_general
-- Total points per carrera across all disciplines.
-- Returns per-discipline breakdown as JSONB for UI accordion.
-- ═══════════════════════════════════════════════════════════════════════════════

DROP VIEW IF EXISTS public.view_clasificacion_general;

CREATE VIEW public.view_clasificacion_general AS
SELECT
    c.id                                            AS carrera_id,
    c.nombre                                        AS carrera_nombre,
    c.escudo_url,
    COALESCE(SUM(cd.puntos_obtenidos), 0)           AS total_puntos,
    COUNT(cd.id)                                    AS disciplinas_participadas,
    JSONB_AGG(
        JSONB_BUILD_OBJECT(
            'disciplina_id',      d.id,
            'disciplina_nombre',  d.name,
            'genero',             cd.genero,
            'posicion',           cd.posicion,
            'puntos',             cd.puntos_obtenidos
        ) ORDER BY cd.puntos_obtenidos DESC
    ) FILTER (WHERE cd.id IS NOT NULL)              AS detalle_disciplinas
FROM public.carreras c
LEFT JOIN public.clasificacion_disciplina cd ON cd.carrera_id = c.id
LEFT JOIN public.disciplinas d ON d.id = cd.disciplina_id
GROUP BY c.id, c.nombre, c.escudo_url
ORDER BY total_puntos DESC, carrera_nombre ASC;

GRANT SELECT ON public.view_clasificacion_general TO authenticated, anon;

-- Reload PostgREST schema cache
NOTIFY pgrst, 'reload schema';
