-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
-- Migration: Excel Import Staging Tables
-- Date: 2026-03-24
-- Description:
--   Staging layer for Excel file imports. Data flows:
--   Upload .xlsx → parse → stage here → admin reviews → commit to production.
--   Tables:
--   1. excel_imports   — one row per uploaded file (metadata + status)
--   2. excel_import_rows — individual parsed rows with validation results
-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

-- ═══════════════════════════════════════════════════════════════════════════════
-- TABLE: excel_imports
-- Metadata for each uploaded Excel file. One row per upload session.
-- ═══════════════════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS public.excel_imports (
    id              UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    created_at      TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    uploaded_by     UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    uploader_name   TEXT,
    filename        TEXT NOT NULL,
    file_size_bytes INT,
    status          TEXT NOT NULL DEFAULT 'pending'
                    CHECK (status IN ('pending', 'committing', 'committed', 'error', 'cancelled')),
    -- pending:    freshly uploaded, rows staged, not yet reviewed
    -- committing: currently being pushed to production (prevents double-click)
    -- committed:  rows pushed to production tables
    -- error:      unrecoverable parse error
    -- cancelled:  admin discarded
    total_rows      INT DEFAULT 0,
    rows_ok         INT DEFAULT 0,
    rows_warning    INT DEFAULT 0,
    rows_error      INT DEFAULT 0,
    sheet_names     TEXT[],
    commit_at       TIMESTAMPTZ,
    notes           TEXT
);

COMMENT ON TABLE public.excel_imports IS
'Metadata for each uploaded Excel file. One row per upload session.
All parsed data lives in excel_import_rows (linked by import_id).';

CREATE INDEX IF NOT EXISTS idx_excel_imports_status
    ON public.excel_imports(status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_excel_imports_uploaded_by
    ON public.excel_imports(uploaded_by);

ALTER TABLE public.excel_imports ENABLE ROW LEVEL SECURITY;

CREATE POLICY "excel_imports_select_staff"
    ON public.excel_imports FOR SELECT
    USING (
        public.has_role(auth.uid(), 'admin')
        OR public.has_role(auth.uid(), 'data_entry')
    );

CREATE POLICY "excel_imports_insert_staff"
    ON public.excel_imports FOR INSERT
    WITH CHECK (
        public.has_role(auth.uid(), 'admin')
        OR public.has_role(auth.uid(), 'data_entry')
    );

CREATE POLICY "excel_imports_update_staff"
    ON public.excel_imports FOR UPDATE
    USING (
        public.has_role(auth.uid(), 'admin')
        OR public.has_role(auth.uid(), 'data_entry')
    );

CREATE POLICY "excel_imports_delete_admins"
    ON public.excel_imports FOR DELETE
    USING (public.has_role(auth.uid(), 'admin'));


-- ═══════════════════════════════════════════════════════════════════════════════
-- TABLE: excel_import_rows
-- Individual parsed rows from each Excel sheet.
-- row_type distinguishes: 'partido' | 'evento' | 'roster'
-- ═══════════════════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS public.excel_import_rows (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    import_id       UUID NOT NULL REFERENCES public.excel_imports(id) ON DELETE CASCADE,
    sheet_name      TEXT NOT NULL,
    row_number      INT NOT NULL,
    row_type        TEXT NOT NULL
                    CHECK (row_type IN ('partido', 'evento', 'roster')),
    raw_data        JSONB NOT NULL DEFAULT '{}',
    -- Verbatim parsed cell values (key = normalized column header)
    matched_data    JSONB DEFAULT '{}',
    -- Resolved entity IDs: { carrera_a_id, carrera_b_id, disciplina_id,
    --                         jugador_id, partido_id, equipo_a_or_b, ... }
    validation_status TEXT NOT NULL DEFAULT 'pending'
                    CHECK (validation_status IN ('ok', 'warning', 'error', 'pending')),
    validation_messages JSONB DEFAULT '[]',
    -- Array of { level: 'warning'|'error', field: string, message: string }
    committed       BOOLEAN DEFAULT false,
    committed_entity_id TEXT,
    -- ID of the production row that was inserted/updated
    created_at      TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

COMMENT ON TABLE public.excel_import_rows IS
'One row per parsed data unit from the Excel import.
raw_data = verbatim Excel cells. matched_data = resolved DB IDs.
validation_status drives the review UI. committed = pushed to production.';

CREATE INDEX IF NOT EXISTS idx_import_rows_import_id
    ON public.excel_import_rows(import_id, validation_status);
CREATE INDEX IF NOT EXISTS idx_import_rows_type
    ON public.excel_import_rows(import_id, row_type);

ALTER TABLE public.excel_import_rows ENABLE ROW LEVEL SECURITY;

CREATE POLICY "import_rows_select_staff"
    ON public.excel_import_rows FOR SELECT
    USING (
        public.has_role(auth.uid(), 'admin')
        OR public.has_role(auth.uid(), 'data_entry')
    );

CREATE POLICY "import_rows_insert_staff"
    ON public.excel_import_rows FOR INSERT
    WITH CHECK (
        public.has_role(auth.uid(), 'admin')
        OR public.has_role(auth.uid(), 'data_entry')
    );

CREATE POLICY "import_rows_update_staff"
    ON public.excel_import_rows FOR UPDATE
    USING (
        public.has_role(auth.uid(), 'admin')
        OR public.has_role(auth.uid(), 'data_entry')
    );

-- Reload PostgREST schema cache
NOTIFY pgrst, 'reload schema';
