-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
-- Migration: Jornadas system for Ajedrez and Tenis de Mesa
-- Date: 2026-04-08
-- Description:
--   Introduces a jornadas model for individual sports that don't fit the
--   1v1 bracket model. A jornada is a session/round (e.g. Ajedrez Round 1,
--   Tenis de Mesa day event) where multiple players compete simultaneously.
--   Results are tracked per participant (jugador + carrera) with final ranking
--   and optional Olympic points override.
-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

-- ─────────────────────────────────────────────────────────────────────────────
-- 1. jornadas — one row per session/round per sport+gender
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.jornadas (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    disciplina_id BIGINT NOT NULL REFERENCES public.disciplinas(id) ON DELETE CASCADE,
    genero        TEXT NOT NULL CHECK (genero IN ('masculino', 'femenino', 'mixto')),
    numero        INT NOT NULL,          -- Round number: 1–5 for Ajedrez, 1 for TdM
    nombre        TEXT,                  -- Label: "Ronda 1", "Jornada Única", etc.
    scheduled_at  TIMESTAMPTZ NOT NULL,
    lugar         TEXT,
    estado        TEXT NOT NULL DEFAULT 'programado'
                  CHECK (estado IN ('programado', 'en_curso', 'finalizado')),
    notas         TEXT,
    created_at    TIMESTAMPTZ DEFAULT now() NOT NULL,

    -- Prevent duplicate rounds per sport+gender
    UNIQUE (disciplina_id, genero, numero)
);

-- ─────────────────────────────────────────────────────────────────────────────
-- 2. jornada_resultados — final ranking per participant per jornada
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.jornada_resultados (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    jornada_id       BIGINT NOT NULL REFERENCES public.jornadas(id) ON DELETE CASCADE,
    jugador_id       BIGINT REFERENCES public.jugadores(id) ON DELETE SET NULL,
    carrera_id       BIGINT NOT NULL REFERENCES public.carreras(id) ON DELETE CASCADE,
    posicion         INT NOT NULL,           -- Final rank (1 = 1st place)
    puntos_olimpicos INT,                    -- NULL = derive from config; explicit = override
    notas            TEXT,
    created_at       TIMESTAMPTZ DEFAULT now() NOT NULL,

    -- Each carrera can only occupy one position per jornada
    UNIQUE (jornada_id, carrera_id, posicion)
);

-- ─────────────────────────────────────────────────────────────────────────────
-- 3. Indexes
-- ─────────────────────────────────────────────────────────────────────────────
CREATE INDEX IF NOT EXISTS idx_jornadas_disciplina_genero
    ON public.jornadas (disciplina_id, genero);

CREATE INDEX IF NOT EXISTS idx_jornadas_scheduled_at
    ON public.jornadas (scheduled_at);

CREATE INDEX IF NOT EXISTS idx_jornada_resultados_jornada
    ON public.jornada_resultados (jornada_id);

CREATE INDEX IF NOT EXISTS idx_jornada_resultados_carrera
    ON public.jornada_resultados (carrera_id);

-- ─────────────────────────────────────────────────────────────────────────────
-- 4. RLS Policies
-- ─────────────────────────────────────────────────────────────────────────────
ALTER TABLE public.jornadas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.jornada_resultados ENABLE ROW LEVEL SECURITY;

-- Public read access
CREATE POLICY "jornadas_select_public" ON public.jornadas
    FOR SELECT USING (true);

CREATE POLICY "jornada_resultados_select_public" ON public.jornada_resultados
    FOR SELECT USING (true);

-- Admin/data_entry write access for jornadas
CREATE POLICY "jornadas_insert_admin" ON public.jornadas
    FOR INSERT WITH CHECK (
        EXISTS (
            SELECT 1 FROM public.profiles
            WHERE id = auth.uid()
            AND (roles @> ARRAY['admin'] OR roles @> ARRAY['data_entry'])
        )
    );

CREATE POLICY "jornadas_update_admin" ON public.jornadas
    FOR UPDATE USING (
        EXISTS (
            SELECT 1 FROM public.profiles
            WHERE id = auth.uid()
            AND (roles @> ARRAY['admin'] OR roles @> ARRAY['data_entry'])
        )
    );

CREATE POLICY "jornadas_delete_admin" ON public.jornadas
    FOR DELETE USING (
        EXISTS (
            SELECT 1 FROM public.profiles
            WHERE id = auth.uid()
            AND roles @> ARRAY['admin']
        )
    );

-- Admin/data_entry write access for resultados
CREATE POLICY "jornada_resultados_insert_admin" ON public.jornada_resultados
    FOR INSERT WITH CHECK (
        EXISTS (
            SELECT 1 FROM public.profiles
            WHERE id = auth.uid()
            AND (roles @> ARRAY['admin'] OR roles @> ARRAY['data_entry'])
        )
    );

CREATE POLICY "jornada_resultados_update_admin" ON public.jornada_resultados
    FOR UPDATE USING (
        EXISTS (
            SELECT 1 FROM public.profiles
            WHERE id = auth.uid()
            AND (roles @> ARRAY['admin'] OR roles @> ARRAY['data_entry'])
        )
    );

CREATE POLICY "jornada_resultados_delete_admin" ON public.jornada_resultados
    FOR DELETE USING (
        EXISTS (
            SELECT 1 FROM public.profiles
            WHERE id = auth.uid()
            AND (roles @> ARRAY['admin'] OR roles @> ARRAY['data_entry'])
        )
    );

-- ─────────────────────────────────────────────────────────────────────────────
-- 5. Realtime
-- ─────────────────────────────────────────────────────────────────────────────
ALTER PUBLICATION supabase_realtime ADD TABLE public.jornadas;
ALTER PUBLICATION supabase_realtime ADD TABLE public.jornada_resultados;

-- ─────────────────────────────────────────────────────────────────────────────
-- 6. Grants
-- ─────────────────────────────────────────────────────────────────────────────
GRANT SELECT ON public.jornadas TO authenticated, anon;
GRANT SELECT ON public.jornada_resultados TO authenticated, anon;
GRANT INSERT, UPDATE, DELETE ON public.jornadas TO authenticated;
GRANT INSERT, UPDATE, DELETE ON public.jornada_resultados TO authenticated;
GRANT USAGE ON SEQUENCE public.jornadas_id_seq TO authenticated;
GRANT USAGE ON SEQUENCE public.jornada_resultados_id_seq TO authenticated;

-- Reload PostgREST schema cache
NOTIFY pgrst, 'reload schema';
