-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
-- Migration: carrera_disciplina — sport enrollment per career
-- Date: 2026-03-30
-- Description:
--   Tracks which carreras (university programs) are enrolled in each
--   disciplina+gender combination. Extracted from the Excel fixture file.
--   Some "equipos" are combined (e.g. "COM. SOCIAL/PSICOLOGÍA" = 2 carreras)
--   — each carrera member gets its own row and full Olympic points independently.
-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

CREATE TABLE IF NOT EXISTS public.carrera_disciplina (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    carrera_id    BIGINT NOT NULL REFERENCES public.carreras(id) ON DELETE CASCADE,
    disciplina_id BIGINT NOT NULL REFERENCES public.disciplinas(id) ON DELETE CASCADE,
    genero        TEXT NOT NULL CHECK (genero IN ('masculino', 'femenino', 'mixto')),
    equipo_nombre TEXT NOT NULL,  -- display name used in matches: "COM. SOCIAL/PSICOLOGÍA"
    created_at    TIMESTAMPTZ DEFAULT NOW() NOT NULL,

    UNIQUE(carrera_id, disciplina_id, genero)
);

COMMENT ON TABLE public.carrera_disciplina IS
'Sport enrollment: which carrera participates in which disciplina+gender.
Populated by importing the Excel fixture file.
Combined teams (e.g. COM. SOCIAL/PSICOLOGÍA) produce multiple rows — one per member carrera.
equipo_nombre is the display label used in partidos.equipo_a/b.';

CREATE INDEX IF NOT EXISTS idx_carrera_disciplina_carrera
    ON public.carrera_disciplina(carrera_id);

CREATE INDEX IF NOT EXISTS idx_carrera_disciplina_disciplina
    ON public.carrera_disciplina(disciplina_id, genero);

-- ─────────────────────────────────────────────────────────────────────────────
-- RLS
-- ─────────────────────────────────────────────────────────────────────────────
ALTER TABLE public.carrera_disciplina ENABLE ROW LEVEL SECURITY;

-- Everyone can see enrollment (drives public career profiles)
CREATE POLICY "cd_select_all"
    ON public.carrera_disciplina FOR SELECT USING (true);

-- Only admin / data_entry can modify enrollment
CREATE POLICY "cd_write_staff"
    ON public.carrera_disciplina FOR ALL
    USING (
        public.has_role(auth.uid(), 'admin')
        OR public.has_role(auth.uid(), 'data_entry')
    )
    WITH CHECK (
        public.has_role(auth.uid(), 'admin')
        OR public.has_role(auth.uid(), 'data_entry')
    );

-- Reload PostgREST schema cache
NOTIFY pgrst, 'reload schema';
