-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
-- Migration: Jugadores Normalization
-- Date: 2026-03-19
-- Description: Normalizes jugadores table to prevent player data duplication across matches.
--              Creates a new jugadores table (master) and roster_partido junction table.
--              Updates RLS policies to prevent roster modifications after match start.
-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

-- PHASE 1: Create backup of old data
-- ═════════════════════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS public.olympics_jugadores_backup AS
SELECT * FROM public.olympics_jugadores;

COMMENT ON TABLE public.olympics_jugadores_backup IS
'Backup of original olympics_jugadores table before normalization. Can be dropped after verification.';


-- PHASE 2: Create new normalized jugadores table
-- ═════════════════════════════════════════════════════════════════════════════════

-- Rename old olympics_jugadores to olympics_jugadores_old temporarily
ALTER TABLE IF EXISTS public.olympics_jugadores RENAME TO olympics_jugadores_old;

-- Create new normalized jugadores table (master player registry)
CREATE TABLE IF NOT EXISTS public.jugadores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL,
    numero INT,
    carrera_id BIGINT REFERENCES public.carreras(id) ON DELETE SET NULL,
    profile_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,

    -- Both carrera_id and profile_id are optional (players may not have user accounts)
    CONSTRAINT jugador_has_nombre CHECK (nombre IS NOT NULL AND nombre != '')
);

COMMENT ON TABLE public.jugadores IS
'Master jugadores table (normalized). Each jugador is stored once, independent of matches.
Linked to optional carrera (team/squad) and/or profile (user account).';

CREATE INDEX IF NOT EXISTS idx_jugadores_nombre ON public.jugadores(nombre);
CREATE INDEX IF NOT EXISTS idx_jugadores_carrera ON public.jugadores(carrera_id);
CREATE INDEX IF NOT EXISTS idx_jugadores_profile ON public.jugadores(profile_id);

-- Enable RLS
ALTER TABLE public.jugadores ENABLE ROW LEVEL SECURITY;

-- RLS Policies for jugadores
DROP POLICY IF EXISTS "Jugadores are viewable by everyone" ON public.jugadores;
CREATE POLICY "Jugadores are viewable by everyone"
    ON public.jugadores FOR SELECT
    USING (TRUE);

DROP POLICY IF EXISTS "Admins can manage jugadores" ON public.jugadores;
CREATE POLICY "Admins can manage jugadores"
    ON public.jugadores FOR INSERT
    WITH CHECK (public.has_role(auth.uid(), 'admin'));

DROP POLICY IF EXISTS "Admins can update jugadores" ON public.jugadores;
CREATE POLICY "Admins can update jugadores"
    ON public.jugadores FOR UPDATE
    USING (public.has_role(auth.uid(), 'admin'));


-- PHASE 3: Create roster_partido junction table
-- ═════════════════════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS public.roster_partido (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    partido_id BIGINT NOT NULL REFERENCES public.partidos(id) ON DELETE CASCADE,
    jugador_id BIGINT NOT NULL REFERENCES public.jugadores(id) ON DELETE CASCADE,
    equipo_a_or_b TEXT NOT NULL CHECK (equipo_a_or_b IN ('equipo_a', 'equipo_b')),
    -- equipo_a_or_b: which side of the match this player is on
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,

    -- Prevent duplicate roster entries
    UNIQUE(partido_id, jugador_id, equipo_a_or_b)
);

COMMENT ON TABLE public.roster_partido IS
'Junction table between partidos and jugadores. Represents the roster (players) for each match.
Enables RLS policies to prevent roster modifications after match starts.';

CREATE INDEX IF NOT EXISTS idx_roster_partido ON public.roster_partido(partido_id);
CREATE INDEX IF NOT EXISTS idx_roster_jugador ON public.roster_partido(jugador_id);
CREATE INDEX IF NOT EXISTS idx_roster_partido_jugador ON public.roster_partido(partido_id, jugador_id);

-- Enable RLS
ALTER TABLE public.roster_partido ENABLE ROW LEVEL SECURITY;

-- RLS Policies for roster_partido
DROP POLICY IF EXISTS "Roster is viewable by everyone" ON public.roster_partido;
CREATE POLICY "Roster is viewable by everyone"
    ON public.roster_partido FOR SELECT
    USING (TRUE);

DROP POLICY IF EXISTS "Can insert roster before match starts" ON public.roster_partido;
CREATE POLICY "Can insert roster before match starts"
    ON public.roster_partido FOR INSERT
    WITH CHECK (
        public.has_role(auth.uid(), 'admin')
        OR public.has_role(auth.uid(), 'data_entry')
    );

-- CRITICAL: Prevent roster modification after match starts
DROP POLICY IF EXISTS "Can update roster only if match is programado" ON public.roster_partido;
CREATE POLICY "Can update roster only if match is programado"
    ON public.roster_partido FOR UPDATE
    USING (
        (public.has_role(auth.uid(), 'admin') OR public.has_role(auth.uid(), 'data_entry'))
        AND EXISTS (
            SELECT 1 FROM public.partidos p
            WHERE p.id = partido_id
            AND p.estado = 'programado'  -- Only modify if still scheduled
        )
    );

-- CRITICAL: Prevent roster deletion after match starts
DROP POLICY IF EXISTS "Can delete roster only if match is programado" ON public.roster_partido;
CREATE POLICY "Can delete roster only if match is programado"
    ON public.roster_partido FOR DELETE
    USING (
        (public.has_role(auth.uid(), 'admin') OR public.has_role(auth.uid(), 'data_entry'))
        AND EXISTS (
            SELECT 1 FROM public.partidos p
            WHERE p.id = partido_id
            AND p.estado = 'programado'
        )
    );

COMMENT ON POLICY "Can update roster only if match is programado" ON public.roster_partido IS
'RLS safeguard: prevents roster updates after match starts (estado != programado).';

COMMENT ON POLICY "Can delete roster only if match is programado" ON public.roster_partido IS
'RLS safeguard: prevents roster deletion after match starts (estado != programado).';


-- PHASE 4: Migrate existing data from olympics_jugadores_old
-- ═════════════════════════════════════════════════════════════════════════════════

DO $$
DECLARE
    old_jugador RECORD;
    new_jugador_id BIGINT;
BEGIN
    -- For each player in old olympics_jugadores
    FOR old_jugador IN
        SELECT DISTINCT
            nombre,
            numero,
            profile_id,
            partido_id
        FROM public.olympics_jugadores_old
        ORDER BY nombre, numero
    LOOP
        -- Check if jugador already exists in normalized table
        SELECT id INTO new_jugador_id
        FROM public.jugadores
        WHERE nombre = old_jugador.nombre
        AND numero IS NOT DISTINCT FROM old_jugador.numero
        AND profile_id IS NOT DISTINCT FROM old_jugador.profile_id;

        -- If not found, create new jugador entry
        IF new_jugador_id IS NULL THEN
            INSERT INTO public.jugadores (nombre, numero, profile_id)
            VALUES (old_jugador.nombre, old_jugador.numero, old_jugador.profile_id)
            RETURNING id INTO new_jugador_id;
        END IF;

        -- Create roster_partido entry for this match
        -- Determine equipo_a or equipo_b based on old equipo field
        INSERT INTO public.roster_partido (partido_id, jugador_id, equipo_a_or_b)
        SELECT
            partido_id,
            new_jugador_id,
            CASE
                WHEN (SELECT equipo FROM public.olympics_jugadores_old oj
                      WHERE oj.nombre = old_jugador.nombre
                      AND oj.numero IS NOT DISTINCT FROM old_jugador.numero
                      LIMIT 1) = 'equipo_a' THEN 'equipo_a'
                ELSE 'equipo_b'
            END
        FROM (SELECT DISTINCT partido_id FROM public.olympics_jugadores_old
              WHERE nombre = old_jugador.nombre
              AND numero IS NOT DISTINCT FROM old_jugador.numero)
        ON CONFLICT (partido_id, jugador_id, equipo_a_or_b) DO NOTHING;
    END LOOP;

    RAISE NOTICE 'Data migration complete: % jugadores and rosters created',
        (SELECT COUNT(*) FROM public.jugadores);
END $$;


-- PHASE 5: Update olympics_eventos to reference new normalized table
-- ═════════════════════════════════════════════════════════════════════════════════

-- Add jugador_id reference if not present, keeping old for backward compatibility
ALTER TABLE public.olympics_eventos
ADD COLUMN IF NOT EXISTS jugador_id_normalized BIGINT
    REFERENCES public.jugadores(id) ON DELETE SET NULL;

-- Migrate events to use normalized jugador
DO $$
BEGIN
    UPDATE public.olympics_eventos oe
    SET jugador_id_normalized = j.id
    FROM public.olympics_jugadores_old oj
    JOIN public.jugadores j ON j.nombre = oj.nombre
        AND j.numero IS NOT DISTINCT FROM oj.numero
        AND j.profile_id IS NOT DISTINCT FROM oj.profile_id
    WHERE oj.id = oe.jugador_id;

    RAISE NOTICE 'olympics_eventos updated with normalized jugador references';
END $$;


-- PHASE 6: Cleanup (comment out if you want to keep old table for verification)
-- ═════════════════════════════════════════════════════════════════════════════════

-- Optional: Drop old table after verification
-- DROP TABLE IF EXISTS public.olympics_jugadores_old CASCADE;

-- For now, keep olympics_jugadores_old renamed for reference and rollback capability
COMMENT ON TABLE public.olympics_jugadores_old IS
'Original olympics_jugadores table before normalization. Kept for verification and rollback.
Can be dropped after confirming data integrity.';


-- PHASE 7: Create helper view for backward compatibility (if needed)
-- ═════════════════════════════════════════════════════════════════════════════════

DROP VIEW IF EXISTS public.vw_olympics_jugadores CASCADE;

CREATE VIEW public.vw_olympics_jugadores AS
SELECT
    j.id,
    j.nombre,
    j.numero,
    j.profile_id,
    j.carrera_id,
    rp.partido_id,
    rp.equipo_a_or_b as equipo,
    j.created_at
FROM public.jugadores j
LEFT JOIN public.roster_partido rp ON rp.jugador_id = j.id;

COMMENT ON VIEW public.vw_olympics_jugadores IS
'Backward compatibility view. Reconstructs the old olympics_jugadores structure from normalized tables.
Use this if frontend code still expects partido_id in jugadores rows.';

-- Grant permissions on view
GRANT SELECT ON public.vw_olympics_jugadores TO PUBLIC;
